### ISSUE TITLE
Times are wrong

### ISSUE THREAD

**Issue by mdcleir** [arcsecond-io/public-issues#59] opened 2019-02-26 12:32 UTC
There is something odd with the times that are displayed.
First of all, the times (in UT) are different whether you look on the x-axis, use the red tracking line, or check the bar at the bottom of the page. There are three different UT times. The times seem to be wrong as well. I would be very surprised if sun sets at 5h am in Belgium (which is only 1 hour from UT)
The following screen shot shows what I mean:
![screen shot 2019-02-26 at 13 21 26](https://user-images.githubusercontent.com/45097951/53412589-0fa29100-39ca-11e9-9444-e885782ef602.png)

Also, the local time in Liège (Belgium) should be the same as the current time (Now), since I am living in Belgium...

Finally, the black box in which the UT (etc) of the pointer is displayed is not visible if you go to far to the edge. See:
![screen shot 2019-02-26 at 13 28 12](https://user-images.githubusercontent.com/45097951/53412723-6740fc80-39ca-11e9-8351-444e936ee187.png)

**Comment by onekiloparsec** [comment] 2019-02-26 15:36
Thanks for the bug report. Indeed, this much be checked carefully.

**Comment by onekiloparsec** [comment] 2019-03-17 15:15
Fixed and deployed.

**Comment by mdcleir** [comment] 2019-03-19 15:23
Thanks for fixing the UT times in the plot.
However, I am afraid not all of the issues above have been fixed...
The x-axis of the plot and the pointer (red line) now correspond to each other, but the bar at the bottom still indicates a different time. In the plot it shows 7 pm, while in the bar it shows 7 am!:
![image](https://user-images.githubusercontent.com/45097951/54617743-29337780-4a62-11e9-82cc-ed840cdafc10.png)
Also, the local time in Liège (Belgium) is wrong. It should be the same as the current time (Now), since I am living in Belgium...
Finally, the black box in which the UT (etc) of the pointer is displayed is not visible if you go to far to the edge. See:
![crop](https://user-images.githubusercontent.com/45097951/54618415-47e63e00-4a63-11e9-93cc-6489e448f5f5.jpeg)

**Comment by onekiloparsec** [comment] 2019-03-19 16:46
Definitely I didn't check enough, my bad. I will correct **all** this asap.

**Comment by mdcleir** [comment] 2019-03-21 11:24
> Definitely I didn't check enough, my bad. I will correct **all** this asap.

No problem. There is no rush. It would just be very nice if these things could be fixed at some point :)

**Comment by onekiloparsec** [comment] 2019-03-23 21:39
Well, that was quite a bugfix session... 

I've listed below the things I've fixed. Your bug reports should be inside it. I'd be glad if you check below what's ok for you. :-) Thanks a lot.

* [ ] Fix of pointer (black box) not showing beyond plot rectangle
* [ ] Improved pointer by adding Local time too
* [ ] Improved times by adopting a consistent format throught components
* [ ] Fix of UT time of bottom (Star Tracks) plot
* [ ] Fix of Local time of bottom (Star Tracks) plot, upper Times bar and plot pointers (it is now DST aware too).
* [ ] Improved bottom track bar with the additions of Julian Day, and LMST.
* [ ] Improved search of Observing Site by flattening all diacritic characters (lie... -> Liège)
* [ ] Fixed appearance of twilight colors in the bottom track bar when switching Observing Sites

**Comment by mdcleir** [comment] 2019-03-29 10:55
Thank you for all these bug fixes. This indeed improved a lot of things! However, I am afraid that not yet everything is working as it should... I noticed that the UT times (and local times) on the airmass plot are only correct when using the 24h display mode, but wrong when using e.g. the Sunset/Sunrise mode.
![Screen Shot 2019-03-29 at 10 41 17](https://user-images.githubusercontent.com/45097951/55226557-8c1ccf80-5215-11e9-99b7-83f4329df909.png)

Furthermore, I saw that something odd is happening with the bottom track bar. Sometimes when you click on a position on the bar, the time is wrong, but when you move a little, the time is correct. See screenshots below:
![Screen Shot 2019-03-29 at 10 39 58](https://user-images.githubusercontent.com/45097951/55226970-8ecbf480-5216-11e9-9554-6b41475e06e1.png)
![Screen Shot 2019-03-29 at 10 40 12](https://user-images.githubusercontent.com/45097951/55226971-8f648b00-5216-11e9-8ad4-1b2562d70469.png)
A slight movement gives a difference of 4 hours...

**Comment by onekiloparsec** [comment] 2019-03-29 12:19
Thanks so much for your help ! I will look asap. I much improved my tests coverage, and this morning I started those of the `NightSlider` component, the "bar" with the times !

**Comment by onekiloparsec** [comment] 2019-03-30 17:08
The cause of the first bug has been identifier: a switch between evening and morning hour... damn. It will be deployed once the next one is also fixed.

**Comment by onekiloparsec** [comment] 2019-03-30 18:42
Second bug identified and fixed. Will cover with tests and redeploy.

**Comment by onekiloparsec** [comment] 2019-03-31 10:30
Covered with tests, and deployed. I will close this issue for now.

**Closed by onekiloparsec** 2019-03-31 10:30 UTC
Labels: bug, frontend

**Comment by mdcleir** [comment] 2019-04-03 16:27
Thanks for fixing these issues.
With these fixes, however, 2 new problems appeared:
-The slider does not change when you go from Sunset/Sunrise to e.g. 24h (I am not sure if that is supposed to be like this or not).
-I cannot change to another observatory anymore. I can search for the observatory, but cannot click on the observatory in the list... 
Should I open a new issue for this?

**Comment by onekiloparsec** [comment] 2019-04-03 17:06
Thanks for the new bug reports. New issues #63 and #62. :-) I'm on it.

**Comment by onekiloparsec** [comment] 2019-04-03 19:06
As far as I can tell, these 2 new bugs are fixed too. You need to (force?) reload your page to enjoy the updated version.

**Comment by mdcleir** [comment] 2019-04-08 11:23
Thank you!
